// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package sqlcs

import (
	"database/sql"
	"time"
)

type User struct {
	ID           string
	Email        string
	Name         string
	PasswordHash string
	VerifyToken  string
	Status       string
	LastLoginAt  sql.NullTime
	Archived     bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type UserRetryCount struct {
	ID          string
	UserID      string
	RetryCount  int64
	LastRetryAt sql.NullTime
	CreatedAt   time.Time
}

type UserSession struct {
	ID             string
	UserID         string
	Token          string
	TokenExpiredAt time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
